cameras:
  - name: IntelRealSenseD455
    serial_no: "_231622302329"
    imu: true
    vslam: true
    stereo_profile: "848x480x60"
  - name: IntelRealSenseD455_2
    serial_no: "_231622302574"
    imu: false
    vslam: false
  # - name: IntelRealSenseD435
  #   serial_no: "_827312071735"
  #   imu: false
  #   vslam: false
  #   stereo_profile: "640x480x60"
  #   color_profile: "640x480x60"
